# Generated by Django 2.0.5 on 2018-07-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_field', models.CharField(choices=[('one', 'One'), ('two', 'Two')], max_length=10)),
            ],
        ),
    ]
